Controllers/ApplicationController.cs
using BetterWorld.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace BetterWorld.Controllers
{
    public class ApplicationController : Controller
    {
        BetterWorldDbContext _dbContext = new BetterWorldDbContext();


        // GET: ApplicationController
        [Authorize(Policy = "View")]
        public async Task<IActionResult> Index()
        {
            var applicationList = await _dbContext.Application
                .Include(x => x.Job)
                .Include(j => j.User)
                .Select(x => new ApplicationViewModel
                {
                    Id = x.Id,
                    Name = x.User.UserName,
                    Email = x.Email,
                    JobId = x.JobId,
                    JobName = x.Job.Title
                })
                .ToListAsync();

            return View(applicationList);
        }

        // GET: ApplicationController/Create

        [Authorize(Policy = "Seeker")]
        public async Task<IActionResult> Apply(int id)
        {
            var job = await _dbContext.Jobs
                .Select(x => new JobViewModel
                {
                    Id = x.Id,
                    Title = x.Title
                })
                .FirstOrDefaultAsync(x => x.Id == id);

            if (job == null)
            {
                return NotFound();
            }

            var jobs = await _dbContext.Jobs
                .Select(x => new JobViewModel
                {
                    Id = x.Id,
                    Title = x.Title
                })
                .ToListAsync();

            ViewBag.Jobs = new SelectList(jobs, "Id", "Title");

            return View();
        }


        // POST: ApplicationController/Create
        [Authorize(Policy = "Seeker")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Apply(ApplicationViewModel avm)
        {
            try
            {
                using (var memoryStream = new MemoryStream())
                {
                    await avm.CVFile.CopyToAsync(memoryStream);
                    var entity = new Application
                    {
                        UserId = Convert.ToInt32(HttpContext.User.Claims.ElementAt(1).Value),
                        Email = avm.Email,
                        CV = memoryStream.ToArray(),
                        CVFileName = avm.CVFile.FileName,
                        CVContentType = avm.CVFile.ContentType,
                        JobId = avm.JobId
                    };

                    _dbContext.Application.Add(entity);
                    await _dbContext.SaveChangesAsync();
                }

                return RedirectToAction(nameof(Index));
            }

            catch
            {
                var jobs = await _dbContext.Jobs
                .Select(x => new JobViewModel
                {
                    Id = x.Id,
                    Title = x.Title
                })
                .ToListAsync();

                ViewBag.Jobs = jobs;
                return View(avm);
            }
        }

        // GET: ApplicationController/Details/5
        [Authorize(Policy = "View")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var applicationDetails = await _dbContext.Application
                .Include(x => x.Job)
                .Include(j => j.User)
                .Select(x => new ApplicationViewModel
                {
                    Id = x.Id,
                    Name = x.User.UserName,
                    Email = x.Email,
                    JobId = x.JobId,
                    JobName = x.Job.Title,
                    CVFileName = x.CVFileName,
                    CVContentType = x.CVContentType
                })
                .FirstOrDefaultAsync(x => x.Id == id);

            if (applicationDetails == null)
            {
                return NotFound();
            }

            return View(applicationDetails);
        }
        [HttpPost]
        public ActionResult Delete(int id, ApplicationViewModel ovm)
        {
            try
            {
                var entity = _dbContext.Application.Where(x => x.Id == id).FirstOrDefault();

                _dbContext.Application.Remove(entity);
                _dbContext.SaveChanges();

                return RedirectToAction(nameof(Application));
            }
            catch
            {
                return View();
            }
        }

        // GET: ApplicationController/DownloadCV/5
        public async Task<IActionResult> DownloadCV(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var application = await _dbContext.Application.FirstOrDefaultAsync(x => x.Id == id);

            if (application == null || application.CV == null)
            {
                return NotFound();
            }

            return File(application.CV, application.CVContentType, application.CVFileName);
        }

    }
}

Controllers/OranisationController.cs
using BetterWorld.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BetterWorld.Controllers
{
    public class OrganizationController : Controller
    {
        BetterWorldDbContext db_context = new BetterWorldDbContext();
        // GET: OrganizationController
        [Authorize(Policy = "View")]
        public ActionResult Index()
        {
            var org_list = db_context.Organizations.ToList();
            if (org_list != null)
            {
                var mapped_list = org_list.Select(x => new OrganizationViewModel()
                {
                    Id = x.Id,
                    Name = x.Name,
                    Address = x.Address,
                    ContactNo = x.ContactNo.ToString(),
                }).ToList();
                return View(mapped_list);
            }
            else
            {
                IEnumerable<OrganizationViewModel> list = Enumerable.Empty<OrganizationViewModel>();
                return View(list);
            }
        }

        // GET: OrganizationController/Details/5
        [Authorize(Policy = "View")]
        public ActionResult Details(int id)
        {
            var org_detail = db_context.Organizations.Where(x => x.Id == id)
                .FirstOrDefault();
            var mapped_detail = new OrganizationViewModel();
            mapped_detail.Id = org_detail.Id;
            mapped_detail.Name = org_detail.Name;
            mapped_detail.Address = org_detail.Address;
            mapped_detail.ContactNo = org_detail.ContactNo.ToString();
            return View(mapped_detail);
        }

        // GET: OrganizationController/Create
        [Authorize(Policy = "Recruiter")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: OrganizationController/Create
        [Authorize(Policy = "Recruiter")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(OrganizationViewModel ovm)
        {
            try
            {

                var entity = new Organization();
                entity.Id = ovm.Id;
                entity.Name = ovm.Name;
                entity.Address = ovm.Address;
                entity.ContactNo = Convert.ToInt32(ovm.ContactNo);

                db_context.Organizations.Add(entity);
                db_context.SaveChanges();
                
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: OrganizationController/Edit/5
        [Authorize(Policy = "Recruiter")]
        public ActionResult Edit(int id)
        {
            var edit_detail = db_context.Organizations.Where(x => x.Id == id).FirstOrDefault();

            var mapped_detail = new OrganizationViewModel();

            mapped_detail.Id = edit_detail.Id;
            mapped_detail.Name = edit_detail.Name;
            mapped_detail.Address = edit_detail.Address;
            mapped_detail.ContactNo = edit_detail.ContactNo.ToString();

            return View(mapped_detail);
        }

        // POST: OrganizationController/Edit/5
        [Authorize(Policy = "Recruiter")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, OrganizationViewModel ovm)
        {
            try
            {
                var entity = new Organization();

                entity.Id = id;
                entity.Name = ovm.Name;
                entity.ContactNo = Convert.ToInt32(ovm.ContactNo);
                entity.Address = ovm.Address;

                db_context.Organizations.Update(entity); 
                db_context.SaveChanges();

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: OrganizationController/Delete/5
        [Authorize(Policy = "Recruiter")]
        public ActionResult Delete(int id)
        {
            var org_detail = db_context.Organizations.Where(x => x.Id == id)
                .FirstOrDefault();
            var mapped_detail = new OrganizationViewModel();
            mapped_detail.Id = org_detail.Id;
            mapped_detail.Name = org_detail.Name;
            mapped_detail.Address = org_detail.Address;
            mapped_detail.ContactNo = org_detail.ContactNo.ToString();
            return View(mapped_detail);
        }

        // POST: OrganizationController/Delete/5
        [Authorize(Policy = "Recruiter")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, OrganizationViewModel ovm)
        {
            try
            {
                var entity = db_context.Organizations.Where(x => x.Id == id).FirstOrDefault();  

                db_context.Organizations.Remove(entity);
                db_context.SaveChanges();

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();   
            }
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="title" content="Better World Employment Services">
    @using BetterWorld.Models;
    <title>@ViewData["Title"] - Better World</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Yeseva+One&display=swap" rel="stylesheet">
    <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
        <symbol id="bootstrap" viewBox="0 0 118 94">
            <path fill-rule="evenodd" clip-rule="evenodd"
                d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z">
            </path>
        </symbol>
        <symbol id="home" viewBox="0 0 576 512">
            <path
                d="M575.8 255.5c0 18-15 32.1-32 32.1h-32l.7 160.2c.2 35.5-28.5 64.3-64 64.3H128.1c-35.3 0-64-28.7-64-64V287.6H32c-18 0-32-14-32-32.1c0-9 3-17 10-24L266.4 8c7-7 15-8 22-8s15 2 21 7L564.8 231.5c8 7 12 15 11 24zM352 224a64 64 0 1 0 -128 0 64 64 0 1 0 128 0zm-96 96c-44.2 0-80 35.8-80 80c0 8.8 7.2 16 16 16H384c8.8 0 16-7.2 16-16c0-44.2-35.8-80-80-80H256z" />
        </symbol>
        <symbol id="user" viewBox="0 0 448 512">
            <path
                d="M224 256A128 128 0 1 0 224 0a128 128 0 1 0 0 256zm-45.7 48C79.8 304 0 383.8 0 482.3C0 498.7 13.3 512 29.7 512H418.3c16.4 0 29.7-13.3 29.7-29.7C448 383.8 368.2 304 269.7 304H178.3z" />
        </symbol>
        <symbol id="info" viewBox="0 0 512 512">
            <path
                d="M256 512A256 256 0 1 0 256 0a256 256 0 1 0 0 512zM216 336h24V272H216c-13.3 0-24-10.7-24-24s10.7-24 24-24h48c13.3 0 24 10.7 24 24v88h8c13.3 0 24 10.7 24 24s-10.7 24-24 24H216c-13.3 0-24-10.7-24-24s10.7-24 24-24zm40-208a32 32 0 1 1 0 64 32 32 0 1 1 0-64z" />
        </symbol>
        <symbol id="facebook" viewBox="0 0 16 16">
            <path
                d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z">
            </path>
        </symbol>
        <symbol id="instagram" viewBox="0 0 16 16">
            <path
                d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z">
            </path>
        </symbol>
        <symbol id="twitter" viewBox="0 0 16 16">
            <path
                d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z">
            </path>
        </symbol>
    </svg>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.min.css" />
    <link rel="stylesheet" href="https://fontawesome.com/icons/user?f=classic&s=solid&sz=lg&rt=flip-horizontal" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BetterWorld.styles.css" asp-append-version="true" />
    <link rel="x-icon" type="image/png" href="~/img/Betterworld.png">

</head>

<body>
    @using System.Security.Claims
    <div class="loader">
        <div></div>
        <div></div>
        <div></div>
        <div></div>
    </div>

    <header>
        <nav class="navbar navbar-expand-lg navbar-light">

            <div class="container">
                <a class="navbar-brand d-flex align-items-center" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/Img/Betterworld.png" alt="Better World" width="70px" height="70px">
                </a>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Job" asp-action="Index">Jobs</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Organization" asp-action="Index">Organizations</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Application" asp-action="Index">Applications</a>
                        </li>
                    </ul>
                    <form class="d-flex" asp-controller="Search" asp-action="Index" method="get">
                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search"
                            name="searchTerm">
                        <button class="search-button">
                            <span>
                                <svg viewBox="0 0 24 24" height="24" width="24" xmlns="http://www.w3.org/2000/svg">
                                    <path
                                        d="M9.145 18.29c-5.042 0-9.145-4.102-9.145-9.145s4.103-9.145 9.145-9.145 9.145 4.103 9.145 9.145-4.102 9.145-9.145 9.145zm0-15.167c-3.321 0-6.022 2.702-6.022 6.022s2.702 6.022 6.022 6.022 6.023-2.702 6.023-6.022-2.702-6.022-6.023-6.022zm9.263 12.443c-.817 1.176-1.852 2.188-3.046 2.981l5.452 5.453 3.014-3.013-5.42-5.421z">
                                    </path>
                                </svg>
                            </span>
                        </button>
                    </form>

                    <div class="d-flex">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <span class="nav-item dropdown">
                                <a class="nav-link" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    <div class="tooltip-container">
                                        <svg class="bi" width="24" height="24">
                                            <use xlink:href="#user"></use>
                                        </svg>
                                        <span class="tooltip">@User.Identity.Name</span>
                                    </div>
                                </a>
                            </span>
                            <button id="SignoutButton" class="Btn" style="margin-top: 17px; margin-left: -5px;">
                                <div class="sign"><svg viewBox="0 0 512 512">
                                        <path
                                            d="M217.9 105.9L340.7 228.7c7.2 7.2 11.3 17.1 11.3 27.3s-4.1 20.1-11.3 27.3L217.9 406.1c-6.4 6.4-15 9.9-24 9.9c-18.7 0-33.9-15.2-33.9-33.9l0-62.1L32 320c-17.7 0-32-14.3-32-32l0-64c0-17.7 14.3-32 32-32l128 0 0-62.1c0-18.7 15.2-33.9 33.9-33.9c9 0 17.6 3.6 24 9.9zM352 416l64 0c17.7 0 32-14.3 32-32l0-256c0-17.7-14.3-32-32-32l-64 0c-17.7 0-32-14.3-32-32s14.3-32 32-32l64 0c53 0 96 43 96 96l0 256c0 53-43 96-96 96l-64 0c-17.7 0-32-14.3-32-32s14.3-32 32-32z">
                                        </path>
                                    </svg></div>
                                <div class="text">Logout</div>
                            </button>
                        }
                        else
                        {
                            <button class="Btn" onclick="window.location.href='/User/Login'">

                                <div class="sign"><svg viewBox="0 0 512 512">
                                        <path
                                            d="M217.9 105.9L340.7 228.7c7.2 7.2 11.3 17.1 11.3 27.3s-4.1 20.1-11.3 27.3L217.9 406.1c-6.4 6.4-15 9.9-24 9.9c-18.7 0-33.9-15.2-33.9-33.9l0-62.1L32 320c-17.7 0-32-14.3-32-32l0-64c0-17.7 14.3-32 32-32l128 0 0-62.1c0-18.7 15.2-33.9 33.9-33.9c9 0 17.6 3.6 24 9.9zM352 416l64 0c17.7 0 32-14.3 32-32l0-256c0-17.7-14.3-32-32-32l-64 0c-17.7 0-32-14.3-32-32s14.3-32 32-32l64 0c53 0 96 43 96 96l0 256c0 53-43 96-96 96l-64 0c-17.7 0-32-14.3-32-32s14.3-32 32-32z">
                                        </path>
                                    </svg></div>

                                <div class="text">Login</div>
                            </button>
                        }
                    </div>
                </div>
            </div>
        </nav>
    </header>

    <div class="mx-auto">
        <main role="main">
            @RenderBody()
        </main>
    </div>


    <footer style="height: 30px;">
        <nav class="navbar navbar-expand-lg  navbar-light">
            <div class="container">
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item"><a href="~/Home/Index" class="nav-link px-2 text-body-secondary">Home</a>
                        </li>
                        <li class="nav-item"><a asp-area="" asp-controller="Home" asp-action="About"
                                class="nav-link px-2 text-body-secondary">About</a></li>
                        <li class="nav-item"><a asp-area="" asp-controller="Home" asp-action="Service"
                                class="nav-link px-2 text-body-secondary">Services</a></li>
                        <li class="nav-item"><a asp-area="" asp-controller="Home" asp-action="Privacy"
                                class="nav-link px-2 text-body-secondary">Privacy Policy</a></li>
                    </ul>
                    <ul class="nav col-md-4 d-flex justify-content-end">
                        <li class="ms-3"><button class="button" type="button">
                                <svg class="bi" width="24" height="24">
                                    <use xlink:href="#twitter"></use>
                                </svg>
                            </button>
                        </li>
                        <li class="ms-3"><button class="button" type="button">
                                <svg class="bi" width="24" height="24">
                                    <use xlink:href="#instagram"></use>
                                </svg></button></li>
                        <li class="ms-3"><button class="button"><svg class="bi" width="24" height="24">
                                    <use xlink:href="#facebook"></use>
                                </svg></button></li>
                    </ul>
                </div>
            </div>
        </nav>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/Logout.js" asp-append-version="true"></script>
    <script src="~/js/Loader.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>